# Generated by Django 3.1.5 on 2021-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountid', models.CharField(db_column='AccountID', max_length=20, primary_key=True, serialize=False)),
                ('businesstype', models.CharField(db_column='BusinessType', max_length=15)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accountaddress',
            fields=[
                ('emailaddressid', models.CharField(db_column='EmailAddressID', max_length=10, primary_key=True, serialize=False)),
                ('emailaddress', models.CharField(db_column='EmailAddress', max_length=25)),
            ],
            options={
                'db_table': 'accountaddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accountpaymentinforel',
            fields=[
                ('accountpaymentinforelid', models.CharField(db_column='AccountPaymentInfoRelID', max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'accountpaymentinforel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.CharField(db_column='AddressID', max_length=10, primary_key=True, serialize=False)),
                ('addressline1', models.CharField(blank=True, db_column='AddressLine1', max_length=25, null=True)),
                ('addressline2', models.CharField(blank=True, db_column='AddressLine2', max_length=25, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=25, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=8, null=True)),
                ('lastupdate', models.DateField(blank=True, db_column='LastUpdate', null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companyentity',
            fields=[
                ('companyentityid', models.CharField(db_column='CompanyEntityID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=25, null=True)),
            ],
            options={
                'db_table': 'companyentity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companyentityaddressrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'companyentityaddressrel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('passwordid', models.CharField(db_column='PasswordID', max_length=5, primary_key=True, serialize=False)),
                ('currentpassword', models.CharField(blank=True, db_column='CurrentPassword', max_length=20, null=True)),
                ('datechanged', models.DateField(blank=True, db_column='DateChanged', null=True)),
            ],
            options={
                'db_table': 'password',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paymentinfo',
            fields=[
                ('cardid', models.CharField(db_column='CardID', max_length=20, primary_key=True, serialize=False)),
                ('paymenttype', models.CharField(blank=True, db_column='PaymentType', max_length=15, null=True)),
            ],
            options={
                'db_table': 'paymentinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.CharField(db_column='PersonID', max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=20, null=True)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=20, null=True)),
                ('projectmanagerid', models.CharField(blank=True, db_column='ProjectManagerID', max_length=20, null=True)),
                ('datecreated', models.DateField(blank=True, db_column='DateCreated', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('lastupdate', models.DateField(blank=True, db_column='LastUpdate', null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('provid', models.CharField(db_column='ProvID', max_length=10, primary_key=True, serialize=False)),
                ('provname', models.CharField(blank=True, db_column='ProvName', max_length=25, null=True)),
                ('abbreviation', models.CharField(blank=True, db_column='Abbreviation', max_length=2, null=True)),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roletype',
            fields=[
                ('roleid', models.CharField(db_column='RoleID', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=20, null=True)),
                ('dateadded', models.DateField(blank=True, db_column='DateAdded', null=True)),
            ],
            options={
                'db_table': 'roletype',
                'managed': False,
            },
        ),
    ]
