# Generated by Django 3.1.5 on 2021-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.CharField(db_column='ProductID', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=30, null=True)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=50, null=True)),
                ('weight', models.CharField(blank=True, db_column='Weight', max_length=30, null=True)),
                ('weightmeasurecode', models.CharField(blank=True, db_column='WeightMeasureCode', max_length=30, null=True)),
                ('rentalcost', models.CharField(blank=True, db_column='RentalCost', max_length=30, null=True)),
                ('hexcolour', models.CharField(blank=True, db_column='HexColour', max_length=30, null=True)),
                ('dateadded', models.DateField(blank=True, db_column='DateAdded', null=True)),
                ('dateremoved', models.DateField(blank=True, db_column='DateRemoved', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=15, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productcategory',
            fields=[
                ('productcategoryid', models.CharField(db_column='ProductCategoryID', max_length=5, primary_key=True, serialize=False)),
                ('productcategoryname', models.CharField(blank=True, db_column='ProductCategoryName', max_length=20, null=True)),
                ('datemodified', models.DateField(blank=True, db_column='DateModified', null=True)),
            ],
            options={
                'db_table': 'productcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subproductcategory',
            fields=[
                ('subproductcategoryid', models.CharField(db_column='SubProductCategoryID', max_length=50, primary_key=True, serialize=False)),
                ('subproductcategoryname', models.CharField(blank=True, db_column='SubProductCategoryName', max_length=20, null=True)),
                ('datemodified', models.DateField(blank=True, db_column='DateModified', null=True)),
            ],
            options={
                'db_table': 'subproductcategory',
                'managed': False,
            },
        ),
    ]
