# Generated by Django 3.1.5 on 2021-04-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountid', models.CharField(db_column='AccountID', max_length=20, primary_key=True, serialize=False)),
                ('businesstype', models.CharField(db_column='BusinessType', max_length=15)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accountaddress',
            fields=[
                ('emailaddressid', models.CharField(db_column='EmailAddressID', max_length=10, primary_key=True, serialize=False)),
                ('emailaddress', models.CharField(db_column='EmailAddress', max_length=25)),
            ],
            options={
                'db_table': 'accountaddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accountpaymentinforel',
            fields=[
                ('accountpaymentinforelid', models.CharField(db_column='AccountPaymentInfoRelID', max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'accountpaymentinforel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceid', models.CharField(db_column='InvoiceID', max_length=10, primary_key=True, serialize=False)),
                ('dategenerated', models.DateField(blank=True, db_column='DateGenerated', null=True)),
                ('paymentdue', models.DateField(db_column='PaymentDue')),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderproduct',
            fields=[
                ('ordered', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'orderproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.CharField(db_column='OrderID', max_length=15, primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('orderrecieveddate', models.DateField(auto_now_add=True, db_column='OrderRecievedDate', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('statusdatechanged', models.DateField(blank=True, db_column='StatusDateChanged', null=True)),
                ('referenceorderid', models.CharField(blank=True, db_column='ReferenceOrderID', max_length=15, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('passwordid', models.CharField(db_column='PasswordID', max_length=5, primary_key=True, serialize=False)),
                ('currentpassword', models.CharField(blank=True, db_column='CurrentPassword', max_length=20, null=True)),
                ('datechanged', models.DateField(blank=True, db_column='DateChanged', null=True)),
            ],
            options={
                'db_table': 'password',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.CharField(db_column='PaymentID', max_length=10, primary_key=True, serialize=False)),
                ('paymentdate', models.DateField(blank=True, db_column='PaymentDate', null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paymentinfo',
            fields=[
                ('cardid', models.CharField(db_column='CardID', max_length=20, primary_key=True, serialize=False)),
                ('paymenttype', models.CharField(blank=True, db_column='PaymentType', max_length=15, null=True)),
            ],
            options={
                'db_table': 'paymentinfo',
                'managed': False,
            },
        ),
    ]
