# Generated by Django 3.1.5 on 2021-04-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
