# Generated by Django 3.1.5 on 2021-04-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('oneclickbuy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userprofile',
                'managed': False,
            },
        ),
    ]
