# Generated by Django 3.1.5 on 2021-04-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.CharField(db_column='AddressID', max_length=10, primary_key=True, serialize=False)),
                ('addressline1', models.CharField(blank=True, db_column='AddressLine1', max_length=25, null=True)),
                ('addressline2', models.CharField(blank=True, db_column='AddressLine2', max_length=25, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=25, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=8, null=True)),
                ('lastupdate', models.DateField(blank=True, db_column='LastUpdate', null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProductrel',
            fields=[
                ('order_productrelid', models.CharField(db_column='Order_ProductRelID', max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'order_productrel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productinventory',
            fields=[
                ('productserialnumber', models.CharField(db_column='ProductSerialNumber', max_length=15, primary_key=True, serialize=False)),
                ('shelf', models.CharField(blank=True, db_column='Shelf', max_length=10, null=True)),
                ('rentalstartdate', models.DateField(blank=True, db_column='RentalStartDate', null=True)),
                ('rentalenddate', models.DateField(blank=True, db_column='RentalendDate', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'productinventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('provid', models.CharField(db_column='ProvID', max_length=10, primary_key=True, serialize=False)),
                ('provname', models.CharField(blank=True, db_column='ProvName', max_length=25, null=True)),
                ('abbreviation', models.CharField(blank=True, db_column='Abbreviation', max_length=2, null=True)),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeid', models.CharField(db_column='StoreID', max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'store',
                'managed': False,
            },
        ),
    ]
